# Generated by Django 3.1.1 on 2020-11-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
