# Generated by Django 3.1.1 on 2020-11-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
