# Generated by Django 3.1.1 on 2020-10-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='photo',
            field=models.ImageField(blank=True, default='media/profile.png', null=True, upload_to='user_photos'),
        ),
    ]
