# Generated by Django 3.1.1 on 2020-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201012_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='photo',
            field=models.ImageField(blank=True, default='user_photos/profile.png', null=True, upload_to='user_photos'),
        ),
    ]
