# Generated by Django 3.1.1 on 2020-10-14 16:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201014_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
