# Generated by Django 3.1.1 on 2020-10-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201014_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_user',
            name='bio',
        ),
    ]
