# Generated by Django 3.1.1 on 2020-11-20 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0016_relationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='created',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='status',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='updated',
        ),
        migrations.AddField(
            model_name='relationship',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relationship',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
